version: "3.9"
   
services:
  envoy:
    build: influxEnvoyStats
    hostname: envoy
    command: "-dba http://influxdb:8086 -dbn envoy -dbp envoy123456 -dbu envoy -e ${ENVOY_HOST:-envoy} -loop ${ENVOY_POLL_INTERVAL:-60s}"
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    environment:
      USER: ${USER}
    depends_on:
      - influxdb

  influxdb:
    image: influxdb
    hostname: influxdb
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: envoy
      DOCKER_INFLUXDB_INIT_PASSWORD: envoy123456
      DOCKER_INFLUXDB_INIT_ORG: envoy
      DOCKER_INFLUXDB_INIT_BUCKET: envoy
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: envoy123456
      INFLUX_HOST: influxdb
      INFLUX_ORG: envoy
      INFLUX_TOKEN: envoy123456
    ports:
      - "8086:8086"

  grafana:
    image: grafana/grafana
    hostname: grafana
    volumes:
      - grafana:/var/lib/grafana
      - ./config/grafana/datasource.yml:/usr/share/grafana/conf/provisioning/datasources/datasource.yml:ro
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
  
volumes:
  influxdb:
  grafana:
